version: "3.8"

services:

  odoo_web: 
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - "8069:8069"
    volumes:
      - ./customs:/customs
      - ./odoo.conf:/etc/odoo/odoo.conf
      - odoo19-web-data:/var/lib/odoo
    environment:
      # هذه متغيرات إذا تريد تستخدمها في odoo (اختياري حسب تكوينك)
      DB_HOST: dpostgres.railway.internalb
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: TXxjPYlxIZUadEigbCXiRijPjONUzQkh
    restart: always

volumes:
  odoo19-web-data:
  odoo19-db-data:
