version: "3.8"

services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: odoo19
      POSTGRES_PASSWORD: odoo
    volumes:
      - odoo19-db-data:/var/lib/postgresql/data
    restart: always

  odoo_web:
    build: 
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - "8069:8069"
    volumes:
      - ./customs:/customs
      - ./odoo.conf:/etc/odoo/odoo.conf
      - odoo19-web-data:/var/lib/odoo
    environment:
      DB_HOST: ${PGHOST}
      DB_PORT: ${PGPORT}
      DB_USER: ${PGUSER}
      DB_PASSWORD: ${PGPASSWORD}
      db_name: ${PGDATABASE}
    restart: always

volumes:
  odoo19-web-data:
  odoo19-db-data:
