version: "3.8"

services:

  odoo_web: 
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8069:8069"
    volumes:
      - ./customs:/customs
      - ./odoo.conf:/etc/odoo/odoo.conf
      - odoo19-web-data:/var/lib/odoo
    environment:
      # هذه متغيرات إذا تريد تستخدمها في odoo (اختياري حسب تكوينك)
      DB_HOST: dpostgres.railway.internalb
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: TXxjPYlxIZUadEigbCXiRijPjONUzQkh
    restart: always

volumes:
  odoo19-web-data:
  odoo19-db-data:


# {"ODOO_EMAIL_FROM":"Odoo <${{ODOO_SMTP_USER}}>","ODOO_SMTP_HOST":"0","ODOO_SMTP_PASSWORD":"0","ODOO_SMTP_PORT_NUMBER":"0","ODOO_SMTP_USER":"0","RAILWAY_RUN_UID":"0","DB_HOST":"${{Postgres.PGHOST}}","db_name":"${{Postgres.PGDATABASE}}","DB_PASSWORD":"${{Postgres.POSTGRES_PASSWORD}}","DB_PORT":"${{Postgres.PGPORT}}","DB_USER":"${{Postgres.POSTGRES_USER}}"}